// <auto-generated />
using System;
using FundingMonitor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FundingMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(FundingMonitorDbContext))]
    [Migration("20260211131805_AddndexByBaseAsset")]
    partial class AddndexByBaseAsset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FundingMonitor.Infrastructure.Data.Entities.NormalizedFundingRateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FundingIntervalHours")
                        .HasColumnType("integer");

                    b.Property<decimal>("FundingRate")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("IndexPrice")
                        .HasColumnType("decimal(18,8)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MarkPrice")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("NextFundingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PredictedNextRate")
                        .HasColumnType("decimal(10,8)");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Exchange");

                    b.HasIndex("NormalizedSymbol");

                    b.HasIndex("BaseAsset", "IsActive");

                    b.HasIndex("NormalizedSymbol", "Exchange")
                        .IsUnique();

                    b.ToTable("FundingRateCurrent");
                });
#pragma warning restore 612, 618
        }
    }
}
