// <auto-generated />
using System;
using FundingMonitor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FundingMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(FundingMonitorDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FundingMonitor.Infrastructure.Data.Entities.CurrentFundingRateDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FundingIntervalHours")
                        .HasColumnType("integer");

                    b.Property<decimal>("FundingRate")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("IndexPrice")
                        .HasColumnType("decimal(18,8)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MarkPrice")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime?>("NextFundingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PredictedNextRate")
                        .HasColumnType("decimal(10,8)");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "BaseAsset");

                    b.HasIndex("NormalizedSymbol", "Exchange")
                        .IsUnique();

                    b.ToTable("CurrentFundingRate");
                });

            modelBuilder.Entity("FundingMonitor.Infrastructure.Data.Entities.HistoricalFundingRateDb", b =>
                {
                    b.Property<string>("Exchange")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedSymbol")
                        .HasColumnType("text");

                    b.Property<DateTime>("FundingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FundingRate")
                        .HasColumnType("decimal(10,8)");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("Exchange", "NormalizedSymbol", "FundingTime");

                    b.HasIndex("FundingTime")
                        .HasDatabaseName("IX_HistoricalFundingRate_Time");

                    b.HasIndex("Exchange", "NormalizedSymbol")
                        .HasDatabaseName("IX_HistoricalFundingRate_Exchange_Symbol");

                    b.ToTable("HistoricalFundingRate");
                });
#pragma warning restore 612, 618
        }
    }
}
